import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

export default function Home() {
  useEffect;
  return (
    <div className={styles.container}>
      <Head>
        <title>is-rec-full</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.highlight}>
          <h1 className={styles.title}>
            🐊 Check if{" "}
            <a
              target="_blank"
              rel="noopener noreferrer"
              href="https://github.com/JJX30/is-rec-full"
            >
              is-rec-full
            </a>{" "}
            🐊
          </h1>
        </div>

        <p className={styles.description}>
          Building muscles and brain power since 1853.
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Student Rec</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Southwest Rec </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </div>
  );
}
